---
  language: go
  sudo: required
  notifications:
    email: true
  go:
    - 1.5
    - 1.6
    - tip
  services:
    - docker
  env:
    global:
      - GO15VENDOREXPERIMENT=1
  install:
    - go get github.com/golang/lint/golint
    - go get -t -d -v ./...
  script:
    - go build -v
    - go vet $(go list ./... | grep -v vendor)
    - test -z "$(golint ./... | grep -v vendor | tee /dev/stderr)"
    - test -z "$(gofmt -s -l . | grep -v vendor | tee /dev/stderr)"
    - make dtest
